site_name: Guía de Diseño Minero
site_url: https://opencontourmining.com/
nav:
    - Guía Rápida de Referencia : https://portal.opencontour.com/js/help/web/viewer.html?file=./quickreferenceguide.pdf
    - Capítulo 1 Introducción: index.md
    - Capítulo 2 Registro  de usuarios: registration.md
    - Capítulo 3 Configuración de  un  proyecto: projectsetup.md
    - Capítulo 4 Módulo central de diseño de minas: MineDesignCoreModule.md
    - Chapter 5 Apilamiento de lixiviación en pilas de Opencontour: stackingModel.md
theme: 
    name: material
    palette:
        primary: green
extra:
  alternate:
    - name: English
      link: /helpguide/en 
      lang: en
    - name: Spanish
      link: /helpguide/es
      lang: es
